### ISSUE TITLE
Entrevista Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-2-entrevista-equipomana#1]
[Reporte de Practica 2 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipomana/files/12554365/Reporte.de.Practica.2.Equipo.Mana.pdf)

**Comment by JeroRoque** [comment]
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
